// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: 103_chirps.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const newChirp = `-- name: NewChirp :one
INSERT INTO chirps (id, created_at, updated_at, body, user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, body, user_id
`

type NewChirpParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Body      string
	UserID    uuid.NullUUID
}

func (q *Queries) NewChirp(ctx context.Context, arg NewChirpParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, newChirp,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Body,
		arg.UserID,
	)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}
