// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: 106_users.sql

package database

import (
	"context"
)

const storePassword = `-- name: StorePassword :exec
UPDATE users
SET hashed_password = $1
WHERE email = $2
`

type StorePasswordParams struct {
	HashedPassword string
	Email          string
}

func (q *Queries) StorePassword(ctx context.Context, arg StorePasswordParams) error {
	_, err := q.db.ExecContext(ctx, storePassword, arg.HashedPassword, arg.Email)
	return err
}
