// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: 110_refresh_tokens.sql

package database

import (
	"context"
	"database/sql"
)

const updateRefreshTokenRevoke = `-- name: UpdateRefreshTokenRevoke :exec
UPDATE refresh_tokens
SET revoked_at = $1
WHERE token = $2
`

type UpdateRefreshTokenRevokeParams struct {
	RevokedAt sql.NullTime
	Token     string
}

func (q *Queries) UpdateRefreshTokenRevoke(ctx context.Context, arg UpdateRefreshTokenRevokeParams) error {
	_, err := q.db.ExecContext(ctx, updateRefreshTokenRevoke, arg.RevokedAt, arg.Token)
	return err
}
