// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: 111_refresh_tokens.sql

package database

import (
	"context"
	"time"
)

const updateRefreshTokenUpdate = `-- name: UpdateRefreshTokenUpdate :exec
UPDATE refresh_tokens
SET updated_at = $1
WHERE token = $2
`

type UpdateRefreshTokenUpdateParams struct {
	UpdatedAt time.Time
	Token     string
}

func (q *Queries) UpdateRefreshTokenUpdate(ctx context.Context, arg UpdateRefreshTokenUpdateParams) error {
	_, err := q.db.ExecContext(ctx, updateRefreshTokenUpdate, arg.UpdatedAt, arg.Token)
	return err
}
