// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: 112_users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const updateUserEmailAndPassword = `-- name: UpdateUserEmailAndPassword :exec
UPDATE users
SET email = $1, hashed_password = $2, updated_at = $3
WHERE id = $4
`

type UpdateUserEmailAndPasswordParams struct {
	Email          string
	HashedPassword string
	UpdatedAt      time.Time
	ID             uuid.UUID
}

func (q *Queries) UpdateUserEmailAndPassword(ctx context.Context, arg UpdateUserEmailAndPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserEmailAndPassword,
		arg.Email,
		arg.HashedPassword,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
