// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: 113_chirps.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteChripWithID = `-- name: DeleteChripWithID :exec
DELETE FROM chirps
WHERE ID = $1
`

func (q *Queries) DeleteChripWithID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteChripWithID, id)
	return err
}
