// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: 114_users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const upgradeUserToChirpyRedFromID = `-- name: UpgradeUserToChirpyRedFromID :exec
UPDATE users
SET is_chirpy_red = true
WHERE id = $1
`

func (q *Queries) UpgradeUserToChirpyRedFromID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, upgradeUserToChirpyRedFromID, id)
	return err
}
